const setErrorCatch = (promise, errorHandler) => promise.catch(errorHandler);

export {
    setErrorCatch,
}